<?php

/**
 * Baseuser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ldap_id
 * @property string $login
 * @property string $pass
 * @property string $name
 * @property string $surname
 * @property string $mail
 * 
 * @method string getLdapId()  Returns the current record's "ldap_id" value
 * @method string getLogin()   Returns the current record's "login" value
 * @method string getPass()    Returns the current record's "pass" value
 * @method string getName()    Returns the current record's "name" value
 * @method string getSurname() Returns the current record's "surname" value
 * @method string getMail()    Returns the current record's "mail" value
 * @method user   setLdapId()  Sets the current record's "ldap_id" value
 * @method user   setLogin()   Sets the current record's "login" value
 * @method user   setPass()    Sets the current record's "pass" value
 * @method user   setName()    Sets the current record's "name" value
 * @method user   setSurname() Sets the current record's "surname" value
 * @method user   setMail()    Sets the current record's "mail" value
 * 
 * @package    rdvz
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Baseuser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('ldap_id', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'length' => '50',
             ));
        $this->hasColumn('login', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'length' => '50',
             ));
        $this->hasColumn('pass', 'string', 40, array(
             'type' => 'string',
             'length' => '40',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('surname', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('mail', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}