csvSuccess:
  has_layout: false

showuaSuccess:
  template: show

oldmeetSuccess:
  template: show

showSuccess:
  javascripts: [jquery-ui-1.7.2.custom.min.js, jquery.contextmenu.r2.js, poll_comment.js]
  stylesheets: [jquery-ui-1.7.2.custom2.css]
