<?php

/**
 * Basemeeting_poll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $date_id
 * @property integer $poll
 * @property integer $uid
 * @property string $comment
 * @property string $participant_name
 * @property meeting_date $meeting_date
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6365 2009-09-15 18:22:38Z jwage $
 */
abstract class Basemeeting_poll extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('meeting_poll');
        $this->hasColumn('date_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('poll', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('participant_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('meeting_date', array(
             'local' => 'date_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}