<?php

/**
 * Basemeeting_date
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mid
 * @property timestamp $date
 * @property string $comment
 * @property meeting $meeting
 * @property Doctrine_Collection $meeting_polls
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6365 2009-09-15 18:22:38Z jwage $
 */
abstract class Basemeeting_date extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('meeting_date');
        $this->hasColumn('mid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('meeting', array(
             'local' => 'mid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('meeting_poll as meeting_polls', array(
             'local' => 'id',
             'foreign' => 'date_id'));
    }
}