<?php

/**
 * Basemeeting_poll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $date_id
 * @property integer $poll
 * @property integer $uid
 * @property string $comment
 * @property string $participant_name
 * @property meeting_date $meeting_date
 * @property user $user
 * 
 * @method integer      getDateId()           Returns the current record's "date_id" value
 * @method integer      getPoll()             Returns the current record's "poll" value
 * @method integer      getUid()              Returns the current record's "uid" value
 * @method string       getComment()          Returns the current record's "comment" value
 * @method string       getParticipantName()  Returns the current record's "participant_name" value
 * @method meeting_date getMeetingDate()      Returns the current record's "meeting_date" value
 * @method user         getUser()             Returns the current record's "user" value
 * @method meeting_poll setDateId()           Sets the current record's "date_id" value
 * @method meeting_poll setPoll()             Sets the current record's "poll" value
 * @method meeting_poll setUid()              Sets the current record's "uid" value
 * @method meeting_poll setComment()          Sets the current record's "comment" value
 * @method meeting_poll setParticipantName()  Sets the current record's "participant_name" value
 * @method meeting_poll setMeetingDate()      Sets the current record's "meeting_date" value
 * @method meeting_poll setUser()             Sets the current record's "user" value
 * 
 * @package    rdvz
 * @subpackage model
 * @author     Romain Deveaud <romain.deveaud@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Basemeeting_poll extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('meeting_poll');
        $this->hasColumn('date_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('poll', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('participant_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('meeting_date', array(
             'local' => 'date_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('user', array(
             'local' => 'uid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}