<?php

/**
 * Baseis_following
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mid
 * @property integer $uid
 * @property meeting $meeting
 * @property user $user
 * 
 * @method integer      getMid()     Returns the current record's "mid" value
 * @method integer      getUid()     Returns the current record's "uid" value
 * @method meeting      getMeeting() Returns the current record's "meeting" value
 * @method user         getUser()    Returns the current record's "user" value
 * @method is_following setMid()     Sets the current record's "mid" value
 * @method is_following setUid()     Sets the current record's "uid" value
 * @method is_following setMeeting() Sets the current record's "meeting" value
 * @method is_following setUser()    Sets the current record's "user" value
 * 
 * @package    rdvz
 * @subpackage model
 * @author     Romain Deveaud <romain.deveaud@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Baseis_following extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('is_following');
        $this->hasColumn('mid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('meeting', array(
             'local' => 'mid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('user', array(
             'local' => 'uid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}