<?php

/**
 * is_following
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rdvz
 * @subpackage model
 * @author     Romain Deveaud <romain.deveaud@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class is_following extends Baseis_following
{
}
