<?php

/**
 * meeting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6365 2009-09-15 18:22:38Z jwage $
 */
class meeting extends Basemeeting
{
  public function save(Doctrine_Connection $conn = null)
  {
    if($this->isNew())
    {    
      $this->setUid(sfContext::getInstance()->getUser()->getProfileVar(sfConfig::get('app_user_id'))) ;

      $min = 0;
      $max = base_convert ('zzz', 36, 10); // hash is 3 chars max
      $id = rand($min, $max) ;
      $hash = base_convert($id, 10, 36) ;

      while(Doctrine::getTable('meeting')->hashExists($hash) || strlen($hash) != 3)
        $hash = base_convert($id, 10, 36) ;

      $this->setHash($hash) ;

      $dt = date_create() ;

      $dt->modify("+3 month") ;
      $this->setDateEnd($dt->format('Y-m-d')) ;

      $dt->modify("+1 month") ;
      $this->setDateDel($dt->format('Y-m-d')) ;
    }

    return parent::save($conn) ; 
  }
}
