<?php

/**
 * user
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6365 2009-09-15 18:22:38Z jwage $
 */
class user extends Baseuser
{
  public function isFollowing($mid)
  {
    $followings = Doctrine::getTable('is_following')->findByUid($this->getId()) ;
    foreach($followings as $f)
      if($f->getMid() == $mid) return true ;

    return false ;
  }
}
