<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('meeting', 'meeting_uid_user_id', array(
             'name' => 'meeting_uid_user_id',
             'local' => 'uid',
             'foreign' => 'id',
             'foreignTable' => 'user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('meeting_date', 'meeting_date_mid_meeting_id', array(
             'name' => 'meeting_date_mid_meeting_id',
             'local' => 'mid',
             'foreign' => 'id',
             'foreignTable' => 'meeting',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('meeting_poll', 'meeting_poll_date_id_meeting_date_id', array(
             'name' => 'meeting_poll_date_id_meeting_date_id',
             'local' => 'date_id',
             'foreign' => 'id',
             'foreignTable' => 'meeting_date',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('meeting_poll', 'meeting_poll_uid_user_id', array(
             'name' => 'meeting_poll_uid_user_id',
             'local' => 'uid',
             'foreign' => 'id',
             'foreignTable' => 'user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('meeting', 'meeting_uid_user_id');
        $this->dropForeignKey('meeting_date', 'meeting_date_mid_meeting_id');
        $this->dropForeignKey('meeting_poll', 'meeting_poll_date_id_meeting_date_id');
        $this->dropForeignKey('meeting_poll', 'meeting_poll_uid_user_id');
    }
}