<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adduser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'ldap_id' => 
             array(
              'type' => 'string',
              'unique' => true,
              'length' => 50,
             ),
             'login' => 
             array(
              'type' => 'string',
              'unique' => true,
              'length' => 50,
             ),
             'pass' => 
             array(
              'type' => 'string',
              'length' => 40,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'surname' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'mail' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'language' => 
             array(
              'type' => 'string',
              'default' => 'fr',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('user');
    }
}