<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('is_following', 'is_following_mid_meeting_id', array(
             'name' => 'is_following_mid_meeting_id',
             'local' => 'mid',
             'foreign' => 'id',
             'foreignTable' => 'meeting',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('is_following', 'is_following_uid_user_id', array(
             'name' => 'is_following_uid_user_id',
             'local' => 'uid',
             'foreign' => 'id',
             'foreignTable' => 'user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('is_following', 'is_following_mid', array(
             'fields' => 
             array(
              0 => 'mid',
             ),
             ));
        $this->addIndex('is_following', 'is_following_uid', array(
             'fields' => 
             array(
              0 => 'uid',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('is_following', 'is_following_mid_meeting_id');
        $this->dropForeignKey('is_following', 'is_following_uid_user_id');
        $this->removeIndex('is_following', 'is_following_mid', array(
             'fields' => 
             array(
              0 => 'mid',
             ),
             ));
        $this->removeIndex('is_following', 'is_following_uid', array(
             'fields' => 
             array(
              0 => 'uid',
             ),
             ));
    }
}